# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f015145d2e3e64d2c9fc2515b676e9e5ec08e34682087a7d7c0a87ff7beb5ea400484494b38c9909c9566f16cb1c4487e6762622a7b37e196faa5e2113ae9fc

test:
  secret_key_base: feafb9f0014229ae459dd742c3b75fef3b442edcfc9a5d56c6dc9288636b99d42006db346a4b48ccbf301fbdcd659160f4665185a6fbea25bb907f7722a94187

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
